version: '3.9'

networks:
  default:
    name: backend

services:

  postgres:
    image: 'postgres:14'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256M'
        reservations:
          cpus: '0.10'
          memory: '32'
      replicas: 1
      restart_policy:
        condition: "on-failure"
        delay: "20s"
        max_attempts: 3
        window: "20s"
