version: '3.9'

networks:
  frontend:
    name: postgres


services:

  weather-service:
    build: ./weather-service
    container_name: 'weather-service'
    image: 'weather-service'
    networks:
      - postgres

  compare-xlsx-service:
    build: ./compare-xlsx-service
    container_name: 'compare-xlsx-service'
    image: 'compare-xlsx-service'

  ui-service:
    build: ./ui-service
    container_name: 'ui-service'
    image: 'ui-service'
    ports:
      - "8080:8080"

