version: "3.9"

networks:
  default:
    name: "backend"

services:

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
        reservations:
          cpus: "0.10"
          memory: "32M"
