spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/weather-service
#    url: jdbc:postgresql://80.78.248.194:5432/weather-service
    username: postgres
    password: root
  liquibase:
    change-log: liquibase/changeLog.xml

app:
  remote:
    url: https://www.gismeteo.ru/weather-sankt-peterburg-4079/
    weather-now: unit unit_temperature_c
    agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
  cron:
    remote-call: 1 0/10 * * * *
