version: '3.9'

networks:
  default:
    name: backend

services:
  ui-service:
    build: ./
    container_name: 'ui-service'
    image: 'ui-service'
    ports:
      - "80:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: "on-failure"
        delay: "20s"
        max_attempts: 3
        window: "20s"
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
        reservations:
          cpus: '0.10'
          memory: '32M'
    healthcheck:
      test: "curl --fail localhost:8080/actuator/health | grep UP || exit 1"
      interval: "20s"
      retries: 5
      start_period: "20s"
      timeout: "20s"

