version: '3.9'

networks:
  default:
    name: backend

services:

  ui-service:
    build: ./
    container_name: 'ui-service'
    image: 'ui-service'
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'
        reservations:
          cpus: '0.10'
          memory: '128M'
