version: '3.9'

networks:
  default:
    name: 'backend'

services:

  weather-service:
    build: ./
    container_name: 'weather-service'
    image: 'weather-service'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '64M'
        reservations:
          cpus: '0.10'
          memory: '16M'
