version: '3.9'

services:

  postgres:
    image: 'postgres:14'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=weather-service'
    ports:
      - "5432:5432"
