app:
  feign:
    compare-xlsx-service-url: compare-xlsx-service:8080

feign:
  client:
    config:
      default:
        loggerLevel: basic
        connectTimeout: 20000
        readTimeout: 100000

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/weather-service
#    url: jdbc:postgresql://80.78.248.194:5432/weather-service
    username: postgres
    password: root
