version: '3.9'

networks:
  default:
    name: backend

services:

  compare-xlsx-service:
    build: ./
    container_name: 'compare-xlsx-service'
    image: 'compare-xlsx-service'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'
        reservations:
          cpus: '0.10'
          memory: '16M'
