version: '3.9'

networks:
  default:
    name: backend

services:
  kafka-test-consumer:
    build: ./
    container_name: 'kafka-test-consumer'
    image: 'kafka-test-consumer'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
        reservations:
          cpus: '0.10'
          memory: '32M'
